version: "2.1"

services:
  router:
    image: "nginx:1-alpine"
    container_name: "playtime-router"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./logs:/var/log/nginx"
      - "./conf:/etc/nginx/conf.d:ro"
      - "../certbot/webroot:/opt/certbot/webroot:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"  # 调整为实际主机证书路径
    restart: "unless-stopped"  # 使用 unless-stopped 便于调试
    networks:
      - default

networks:
  default:
    external:
      name: "playtime_network"